/** @file
 * defines automatically generated by tools/dodef.pl and used by
 * \ref lx_strcpy_r4() and tools/permute.sh
 */
#ifdef DO_PRE0
#define PRE0 prefetch 0x20(%esi)
#else
#define PRE0
#endif

#ifdef DO_PRE1
#define PRE1 prefetch 0x20(%esi)
#else
#define PRE1
#endif

#ifdef DO_PRE2
#define PRE2 prefetch 0x20(%esi)
#else
#define PRE2
#endif

#ifdef DO_PRE3
#define PRE3 prefetch 0x20(%esi)
#else
#define PRE3
#endif

#ifdef DO_PRE4
#define PRE4 prefetch 0x20(%esi)
#else
#define PRE4
#endif

#ifdef DO_PRE5
#define PRE5 prefetch 0x20(%esi)
#else
#define PRE5
#endif

#ifdef DO_PRE6
#define PRE6 prefetch 0x20(%esi)
#else
#define PRE6
#endif

#ifdef DO_PRE7
#define PRE7 prefetch 0x20(%esi)
#else
#define PRE7
#endif

#ifdef DO_PRE8
#define PRE8 prefetch 0x20(%esi)
#else
#define PRE8
#endif

#ifdef DO_PRE9
#define PRE9 prefetch 0x20(%esi)
#else
#define PRE9
#endif

#ifdef DO_PRE10
#define PRE10 prefetch 0x20(%esi)
#else
#define PRE10
#endif

#ifdef DO_PRE11
#define PRE11 prefetch 0x20(%esi)
#else
#define PRE11
#endif

#ifdef DO_PRE12
#define PRE12 prefetch 0x20(%esi)
#else
#define PRE12
#endif

#ifdef DO_PRE13
#define PRE13 prefetch 0x20(%esi)
#else
#define PRE13
#endif

#ifdef DO_PRE14
#define PRE14 prefetch 0x20(%esi)
#else
#define PRE14
#endif

#ifdef DO_PRE15
#define PRE15 prefetch 0x20(%esi)
#else
#define PRE15
#endif

#ifdef DO_PRE16
#define PRE16 prefetch 0x20(%esi)
#else
#define PRE16
#endif

#ifdef DO_PRE17
#define PRE17 prefetch 0x20(%esi)
#else
#define PRE17
#endif

#ifdef DO_PRE18
#define PRE18 prefetch 0x20(%esi)
#else
#define PRE18
#endif

#ifdef DO_PRE19
#define PRE19 prefetch 0x20(%esi)
#else
#define PRE19
#endif

#ifdef DO_PRE20
#define PRE20 prefetch 0x20(%esi)
#else
#define PRE20
#endif

#ifdef DO_PRE21
#define PRE21 prefetch 0x20(%esi)
#else
#define PRE21
#endif

#ifdef DO_PRE22
#define PRE22 prefetch 0x20(%esi)
#else
#define PRE22
#endif

#ifdef DO_PRE23
#define PRE23 prefetch 0x20(%esi)
#else
#define PRE23
#endif

#ifdef DO_PRE24
#define PRE24 prefetch 0x20(%esi)
#else
#define PRE24
#endif

#ifdef DO_PRE25
#define PRE25 prefetch 0x20(%esi)
#else
#define PRE25
#endif

#ifdef DO_PRE26
#define PRE26 prefetch 0x20(%esi)
#else
#define PRE26
#endif

#ifdef DO_PRE27
#define PRE27 prefetch 0x20(%esi)
#else
#define PRE27
#endif

#ifdef DO_PRE28
#define PRE28 prefetch 0x20(%esi)
#else
#define PRE28
#endif

